workflows:
  debug-workflow:
    scripts:
      - name: "debug-script"
        script: "cd $CM_BUILD_DIR/frontend/calmed-tics && chmod +x ./gradlew && ARCHS=arm64 && SDK_NAME=iphoneos && CONFIGURATION=Release && ./gradlew :shared:compileKotlinIosArm64 --stacktrace --info --console=plain"
  ios-build:
    name: ios-build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodemagicAPI
    environment:
      vars:
        APP_STORE_APPLE_ID: 6803588201
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tagware.calmedtics
    scripts:
      - name: "Set up code signing settings on Xcode project"
        script: "xcode-project use-profiles --custom-export-options='{\"testFlightInternalTestingOnly\": true}'"
      - name: "Increment build number"
        script: "cd $CM_BUILD_DIR/frontend/calmed-tics/iosApp && LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number \"$APP_STORE_APPLE_ID\") && if [ -z \"$LATEST_BUILD_NUMBER\" ]; then UPDATED_BUILD_NUMBER=$BUILD_NUMBER; else UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1)); fi && agvtool new-version -all \"$UPDATED_BUILD_NUMBER\""
      - name: "Build ipa for distribution"
        script: "cd $CM_BUILD_DIR/frontend/calmed-tics/iosApp && xcode-project build-ipa --workspace \"$XCODE_WORKSPACE\"  --scheme \"$XCODE_SCHEME\""
    artifacts:
      - frontend/calmed-tics/iosApp/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - CalmEd
        expire_build_submitted_for_review: true
        submit_to_app_store: false
#        cancel_previous_submissions: false
#        release_type: AFTER_APPROVAL
#        copyright: 2026 Tagware Ltd
