# Kotlin
kotlin.code.style=official
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx6g
kotlin.native.jvmArgs=-Xmx6g
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.workers.max=2
android.nonTransitiveRClass=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=true
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true
kotlin.apple.xcodeCompatibility.nowarn=true