# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3g
kotlin.native.jvmArgs=-Xmx6g

# Gradle
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.workers.max=2

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=true

# Apple
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true
kotlin.apple.xcodeCompatibility.nowarn=true