[versions]
#libraries
agp = "9.1.1"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
androidxActivity = "1.13.0"
androidxAppcompat = "1.7.1"
androidxCore = "1.18.0"
androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.2"
androidxDatastore = "1.2.1"
billing = "8.3.0"
stripeAndroid = "23.1.0"

oAuthJavaJwt = "4.5.1"
squareupOkio = "3.17.0"

kotlinxSerializationJson = "1.10.0"
kotlinxCoroutines = "1.10.2"
ktor = "3.4.1"

androidxCredentials = "1.5.0"
googleAndroidLibrariesIdentityGoogleId = "1.2.0"
googleAndroidGmsPlayServicesAuth = "21.5.1"
googlePlayServicesCastFramework = "22.3.1"
multiplatformSettings = "1.3.0"


media3= "1.10.0"
androidxBrowser = "1.10.0"

kotlinxDatetime = "0.7.1"
coil = "3.4.0"

#plugins
kotlin = "2.3.20"
composeMultiplatform = "1.10.3"
composeHotReload = "1.0.0"

ksp = "2.3.6"
koinAnnotations = "2.3.2-Beta1"
koin = "4.2.0"

room = "2.8.4"
sqlite = "2.6.2"
buildConfig = "6.0.9"


[libraries]
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }

oAuthJavaJwt = { module = "com.auth0:java-jwt", version.ref = "oAuthJavaJwt" }

androidxLifecycleViewModelSavedState = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidxLifecycleViewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxLifecycleRuntimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

androidxNavigationCompose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }

androidxDatastore = { module = "androidx.datastore:datastore", version.ref = "androidxDatastore" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }

squareupOkio = { module = "com.squareup.okio:okio", version.ref = "squareupOkio" }

kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesCoreIosArm64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-iosarm64", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesCoreIosSimulatorArm64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-iossimulatorarm64", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesCoreIosX64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64", version.ref = "kotlinxCoroutines" }

ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koinKspCompiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinAndroidXCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinCoreIosArm64 = { module = "io.insert-koin:koin-core-iosarm64", version.ref = "koin" }
koinCoreIosSimulatorArm64 = { module = "io.insert-koin:koin-core-iossimulatorarm64", version.ref = "koin" }
koinCoreIosX64 = { module = "io.insert-koin:koin-core-iosx64", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koinComposeViewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koinAnnotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomCommon = { module = "androidx.room:room-common", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomRuntimeAndroid = { module = "androidx.room:room-runtime-android", version.ref = "room" }
roomRuntimeIosArm64 = { module = "androidx.room:room-runtime-iosarm64", version.ref = "room" }
roomRuntimeIosSimulatorArm64 = { module = "androidx.room:room-runtime-iossimulatorarm64", version.ref = "room" }
roomRuntimeIosX64 = { module = "androidx.room:room-runtime-iosx64", version.ref = "room" }
sqliteBundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqliteWrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }

androidxCredentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidxCredentialsPlayServicesAuth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
googleAndroidLibrariesIdentityGoogleId = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleAndroidLibrariesIdentityGoogleId" }
googleAndroidGmsPlayServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "googleAndroidGmsPlayServicesAuth" }
googlePlayServicesCastFramework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "googlePlayServicesCastFramework" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }

media3Exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3UI = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3Common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3ExoplayerHLS = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3ExoplayerDash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3Database = { module = "androidx.media3:media3-database", version.ref = "media3" }
media3Datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3" }
media3ExoplayerWorkmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "media3" }
androidxBrowser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
billingClient = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
stripeAndroid = { module = "com.stripe:stripe-android", version.ref = "stripeAndroid" }

kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilNetworkKtor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }


