kotlin.code.style=official
exposed_version=1.0.0-rc-4
koin_version=4.2.0-beta2
kotlin_version=2.3.0
ktor_version=3.3.3
logback_version=1.5.23
postgres_version=42.7.8
commons_email2_jakarta_version=2.0.0-M1
java_jwt_version=4.5.0
lib_bcrypt:0.10.2
HikariCP_version:7.0.2
flyway_database_postgresql_version:11.20.0