kotlin.code.style=official
exposed_version=1.4.0
koin_version=4.2.2
kotlin_version=2.4.10
ktor_version=3.5.2
logback_version=1.6.3
postgres_version=42.7.13
commons_email_version=1.6.0
java_jwt_version=4.6.0
jwks_rsa_version=0.24.1
lib_bcrypt=0.10.2
HikariCP_version=7.1.0
flyway_database_postgresql_version=13.3.0
junit_version=6.1.3
mockk_version=1.14.11
stripe_java_version=33.3.0
nimbus_jose_jwt_version=10.9.1
commons_validator=1.11.0