kotlin.code.style=official
exposed_version=1.1.1
koin_version=4.2.0
kotlin_version=2.3.20
ktor_version=3.4.1
logback_version=1.5.23
postgres_version=42.7.10
commons_email_version=1.6.0
java_jwt_version=4.5.1
jwks_rsa_version=0.23.0
lib_bcrypt=0.10.2
HikariCP_version=7.0.2
flyway_database_postgresql_version=12.1.1
junit_version=6.1.0-M1
mockk_version=1.14.9
stripe_java_version=31.5.0-beta.1
nimbus_jose_jwt_version=10.8