[versions]
kotlin = "2.4.20"
ktor = "3.5.2"
exposed = "1.5.0"
koin = "4.2.2"
logback = "1.6.3"
postgres = "42.7.13"
commons-email = "1.6.0"
commons-validator = "1.11.0"
mailtrap = "1.3.0"
java-jwt = "4.6.0"
jwks-rsa = "0.24.1"
bcrypt = "0.10.2"
hikaricp = "7.1.0"
flyway = "13.5.0"
junit = "6.1.3"
mockk = "1.14.11"
nimbus-jwt = "10.9.1"
stripe-java = "33.4.1"

[libraries]
# Ktor Server
ktor-server-compression = { group = "io.ktor", name = "ktor-server-compression", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-default-headers = { group = "io.ktor", name = "ktor-server-default-headers", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-csrf = { group = "io.ktor", name = "ktor-server-csrf", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-sessions = { group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }
ktor-server-request-validation = { group = "io.ktor", name = "ktor-server-request-validation", version.ref = "ktor" }
ktor-server-rate-limit = { group = "io.ktor", name = "ktor-server-rate-limit", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-host-common = { group = "io.ktor", name = "ktor-server-host-common", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

# Ktor Client & Serialization
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Database (Exposed, Postgres, Flyway)
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-java-time = { group = "org.jetbrains.exposed", name = "exposed-java-time", version.ref = "exposed" }
exposed-migration-core= { group = "org.jetbrains.exposed", name = "exposed-migration-core", version.ref = "exposed" }
exposed-migration-jdbc= { group = "org.jetbrains.exposed", name = "exposed-migration-jdbc", version.ref = "exposed" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
flyway-postgres = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }

# Koin Dependency Injection
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }

# Utilities & Email
commons-email = { group = "org.apache.commons", name = "commons-email", version.ref = "commons-email" }
commons-validator = { group = "commons-validator", name = "commons-validator", version.ref = "commons-validator" }
mailtrap = { group = "io.mailtrap", name = "mailtrap-java", version.ref = "mailtrap" }

# Security & JWT
nimbus-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbus-jwt" }
auth0-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "java-jwt" }
auth0-jwks = { group = "com.auth0", name = "jwks-rsa", version.ref = "jwks-rsa" }
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }

# Payments
stripe-java = { group = "com.stripe", name = "stripe-java", version.ref = "stripe-java"}

# Logging
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# Testing
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
ktor-server = [
    "ktor-server-compression", "ktor-server-cors", "ktor-server-default-headers",
    "ktor-server-core", "ktor-server-auth", "ktor-server-auth-jwt", "ktor-server-csrf",
    "ktor-server-content-negotiation", "ktor-server-sessions", "ktor-server-request-validation",
    "ktor-server-rate-limit",
    "ktor-server-resources", "ktor-server-host-common", "ktor-server-status-pages",
    "ktor-server-call-logging", "ktor-server-config-yaml", "ktor-server-netty"
]
ktor-client = [
    "ktor-client-core", "ktor-client-cio", "ktor-client-content-negotiation", "ktor-client-apache"
]
exposed = [
    "exposed-core", "exposed-jdbc", "exposed-dao", "exposed-java-time", "exposed-migration-core", "exposed-migration-jdbc"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
exposed = { id = "org.jetbrains.exposed.plugin", version.ref = "exposed" }